version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 25
  target-branch: main
  reviewers:
  - masahiro04
