version: "3.9"
services:
  web:
    build: .
    command: tail -f /dev/null
    ports:
      - 3000:3000
    environment:
      PLAYWRIGHT_BROWSERS_PATH: /usr/lib/playwright
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/build
